apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: gim-backend-config
  namespace: {{ .Release.Namespace }}
spec:
  healthCheck:
    requestPath: /healthz
    port: 30880
    type: HTTP