serviceAccount:
  create: false
  name: REPLACE_ME

# Migration jobs ServiceAccount and settings
migration:
  serviceAccount:
    create: false
    name: REPLACE_ME
  postDeploy:
    backOffLimit: 5
    ttlSecondsAfterFinished: 3600 # 1h to remove errors

# Loki subchart ServiceAccount
loki:
  serviceAccount:
    create: false

# Loki-minio subchart ServiceAccount
loki-minio:
  serviceAccount:
    create: false

rbac:
  enabled: false

onPrem:
  replicatedRbac:
    enabled: false
  adminUser:
    email: REPLACE_ME
    firstname: REPLACE_ME
    password: REPLACE_ME

gcpMarketplace:
  enabled: true

ingress:
  enabled: true
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: "gce"

front:
  service:
    type: "NodePort"
    port: 80
    nodePort: 30880
    annotations:
      cloud.google.com/neg: '{"ingress": false}'
      cloud.google.com/backend-config: '{"default": "gim-backend-config"}'

observability:
  serviceMonitors:
    enabled: false
  exporters:
    statefulAppExporter:
      enabled: false

logCollector:
  enabled: false

securityContext:
  enabled: true

replicated:
  serviceAccountName: REPLACE_ME

hostname: REPLACE_ME

miscEncryption:
  djangoSecretKey: REPLACE_ME

postgresql:
  port: 5432
  username: REPLACE_ME
  host: REPLACE_ME
  database: REPLACE_ME
  password: REPLACE_ME
  tls:
    mode: REPLACE_ME

redis:
  main:
    port: 6379
    host: REPLACE_ME
